name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [master, ci/devsecops]
  pull_request:
    branches: [master, ci/devsecops]

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ---------- Static Application Security Testing ----------
      - name: Run Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/owasp-top-ten"
        continue-on-error: true

      # ---------- Code Quality & Analysis ----------
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.1.3023-linux.zip
          unzip sonar-scanner.zip -d $HOME
          echo "$HOME/sonar-scanner-4.8.1.3023-linux/bin" >> $GITHUB_PATH

      - name: Run SonarScanner
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=pygoat \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
            -Dsonar.login=${{ env.SONAR_TOKEN }}

      # ---------- Dependency Scanning ----------
      - name: Snyk Scan (Dependencies)
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      # ---------- Secrets Scanning ----------
      - name: Run Gitleaks (Secret Detection)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-git -v
        continue-on-error: true
